version: '3.8'
services:
  backend_test:
    container_name: backend_test
    build:
      context: .
      dockerfile: ./backend/Dockerfile.test
    volumes:
      - ./backend:/backend
      - .env:/backend/.env
      - /backend/node_modules

  frontend_test:
    container_name: frontend_test
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.test
    volumes:
      - ./frontend:/frontend
      - .env:/frontend/.env
      - /frontend/node_modules
    depends_on:
      - backend_test